### ISSUE TITLE
Announce the Events and Solicit Applications from Attendees

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conference#7]
Publicly announce the events and invite people to apply. _(Note: We will still soft-announce on the April 30 IPFS All Hands but won't do a big announcement until we have the website and application forms lined up.)_

- Draft of the Announcements: [Announcements: Working Groups, IPFS Dev Meeting, IPFS Conf](https://drive.google.com/open?id=1ksS3cEang_k3vkHBQTqCePBveGYgulP8WrGA8K8kUSg) in google docs. 
- also see [IPFS Dev Meeting 2018 Planning](https://drive.google.com/open?id=1jv4cmLoYdfmpWeuFwwFZSzLK2zqGsCxl2wzu4g366YU)
- related: Blog Draft on [Governing Protocols and Leading Products](https://drive.google.com/open?id=1jv4cmLoYdfmpWeuFwwFZSzLK2zqGsCxl2wzu4g366YU)

When the blog post goes out, post links on:
- [x] ipfsbot twitter
- [ ] [ipfs-users](https://groups.google.com/forum/#!forum/ipfs-users) mailing list
- [x] an issue on ipfs/ipfs repo (950 followers, 12k "stargazers")

Depends on:
- [x] Create the IPFS and libp2p User Registry (#11, ipfs/pm#626)
- [x] Nail down dates and venue (#1, #2)
- [x] Create Application Forms (#4)
- [x] Publish a blog post announcing the events
- [ ] Make a Website for the Events (#6)

**Comment by VictorBjelkholm** [comment]
Yup, on it

**Comment by VictorBjelkholm** [comment]
Done!

![image](https://user-images.githubusercontent.com/459764/40376288-e07fa086-5de5-11e8-8b37-d170069ba9f3.png)


- https://twitter.com/IPFSbot/status/998964168274403328
- https://twitter.com/IPFSbot/status/998964366077816832
